services:
  backend:
    build:
      context: ./backend
    command: deno run -A --watch main.ts
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    